### ISSUE TITLE
Localize on iOs

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#107]
Hello,

With the new locales.html, texts are not showing up on iOs cause there is an error in the localize function.
: data:text/javascrip…:202 TypeError: undefined is not an object (evaluating 'proto.__localizationCache.messages = {}'))

Have tested it on BrowserStack as usual :laughing: 

![capture du 2017-06-11 11-40-19](https://user-images.githubusercontent.com/15279620/27009990-445cd1ba-4e9b-11e7-9fd0-44829ba455b9.png)

**Comment by Oupsla** [comment]
Using latest version available on v2 branch and polymer 1.9.1

**Comment by masonlouchart** [comment]
First of all, thank you for your contributions @Oupsla !

Second, my apologies for missed it. I didn't guess this change could be an issue and I didn't take the time to test on multiple browsers/devices.
I'll take a look ASAP.

**Comment by masonlouchart** [comment]
I was able to reproduce this issue.

**Comment by Oupsla** [comment]
@masonlouchart No problem I really love this component :+1:

**Comment by Oupsla** [comment]
Related to https://github.com/PolymerElements/app-localize-behavior/issues/92

**Comment by Oupsla** [comment]
Upgrading to latest app-localize-behavior fix the issue
