### ISSUE TITLE
Document differences from PolymerFire's <firebase-auth>

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [convoo/login-fire#110]
How is `<login-fire>` different from PolymerFire's [`<firebase-auth>`](https://github.com/firebase/polymerfire#firebase-auth)? Please document it in `README.md`.

**Comment by sbeleidy** [comment]
`<login-fire>` builds on top of the polymerfire elements by easing all the authentication set up, design, localization and error handling. You can see how it does all that in the demos. 

I'm closing this issue and maybe we can make things clearer in the readme as part of #69.
Thanks.

**Comment by FluorescentHallucinogen** [comment]
Why not focus your efforts on improving `<polymerfire>`? :thinking:
