### ISSUE TITLE
Adding translation for error message

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#111]
Hello,

Would be great to add some texts when a firebase error occurs (like wrong password, user not defined, ...).

![loginfire-translation](https://user-images.githubusercontent.com/15279620/27188064-4ac48552-51ed-11e7-8c09-116cb800e9da.png)

If I got some time this weekend, I'll make a PR about this :smile:

**Comment by sbeleidy** [comment]
I think this is actually one of the blockers to releasing 1.0. This and thoroughly testing the hybrid element. Can't wait to check the PR! (#14)
