### ISSUE TITLE
Width of form change when an error occurs

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#115]
Before error

![loginfireerror1](https://user-images.githubusercontent.com/15279620/27225416-49ca7d98-529a-11e7-8d66-aaac869e70f7.png)

After Error

![loginfireerror2](https://user-images.githubusercontent.com/15279620/27225420-4eb12c9e-529a-11e7-9115-b6912a00d572.png)

**Comment by masonlouchart** [comment]
I confirm, I've already seen it. I though have time to fix it before someone find it but I was wrong... 😢

**Comment by masonlouchart** [comment]
PR #126 merged.
