### ISSUE TITLE
[Android] Logout icon is not hidden on Chrome

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#116]
The iron-icon in login-fire-button is not displayed on iOs (tested on browerStack)

![loginfireicon](https://user-images.githubusercontent.com/15279620/27225468-9bbcf996-529a-11e7-84ea-ee010b0bf88b.png)

**Comment by masonlouchart** [comment]
Could you provide a hosted version of the app you're using please?

Because, if I didn't know you have added an "enter" icon between the provider logo and the text, I would say everything is right.

**Comment by Oupsla** [comment]
For the same app, the enter icon is not rendered on iOs but is rendered in Chrome 

On Chrome (with Nexus 5 selected)
![capture du 2017-06-19 15-08-07](https://user-images.githubusercontent.com/15279620/27286691-5e2c13f0-5501-11e7-9c4c-df7ae44c5f78.png)

On iOs (with browserStack)
![capture du 2017-06-19 15-08-03](https://user-images.githubusercontent.com/15279620/27286677-516d1f56-5501-11e7-9262-000363953a5a.png)


If I got some time, I'll host a minimalist version :+1:

**Comment by masonlouchart** [comment]
IMHO, the `login-fire-button` buttons are not expecting to receive an icon. There already is the auth provider logo. I don't think it exists many icons that have a place into this kind of button (excepted the _"enter"_ icon you've used). In addition, put 2 icons into a single button is quite overkilled.

We can fix this issue plus the issue #120 but I guess it's not a normal use.

Maybe you have many use cases that could open my mind? 🤓

**Comment by Oupsla** [comment]
No for me I don't know why there are 2 icons, the provider logo is enough IHMO.

After some research, I found that is the logout button that is not hidden on Android !

**Comment by masonlouchart** [comment]
Oh OK. I thought you've add an _"enter"_ icon. And it's definitively not the good icon to use! This is the _"input"_ icon and the good one should be _"exit-to-app"_.

I like the title update, completely inverting the issue. 😆 

_[Polymer Iconset Generator](https://poly-icon.appspot.com/?name=myicons&size=24&icon=icons%3Aexit-to-app&icon=icons%3Ainput)_

**Comment by masonlouchart** [comment]
I just tried on a Nexus 5 with Android 4.4 (using BrowserStack) and the exit icons are hidden.

The `login-fire` version used for the test was picked at this point: [commit 3b2216b](https://github.com/convoo/login-fire/commit/3b2216beac58586eb4f0d0893f8bf3559668fb90).
The tests were made running the element directly without optimizations but also running a minified version inside an application.

<img width="441" alt="capture d ecran 2017-06-29 a 23 52 32" src="https://user-images.githubusercontent.com/2325091/27712215-44c6081c-5d26-11e7-8e0c-71b42bd997dc.png">

Please provide a JSBin containing a set of reproducible steps.
