### ISSUE TITLE
Should inputs not be cleared after signIn ?

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#118]
Hello,

I was asking myself if inputs (email + password) should not be cleared after a successful signIn ?
Cause if somebody logout, the form is still filled with his credentials.

And even more the password input should not be cleared after an unsuccessful attempt ?

I'll do a PR, give me your opinion about this !

Thanks

**Comment by sbeleidy** [comment]
I think inputs should be cleared after successful sign in. Not sure about password though. I would usually want it to be cleared or at least selected so that when I type I just retype my password.

If there is a disagreement on this, I think we can add a flag `clear-after-signin` or we can have a clear function and we can fire failed sign in and successful sign in events that the developer can use to call the clear function if they want.

Thoughts?

**Comment by masonlouchart** [comment]
IMHO, inputs should be cleared, at least the password.
The user email can be cleared or not, or we could add a checkbox _"Remember me"_ if you want.

**Comment by sbeleidy** [comment]
I think "Remember me" is on by default the way firebase works. Right?

**Comment by masonlouchart** [comment]
As you prefer. Personally I never check those checkboxes, I use a password manager.

IMHO, when I sign out it's for avoiding people to access my account when I'm not on the computer or for switching to another account. So I never use the _"Remember me"_ feature.

**Comment by Oupsla** [comment]
IMHO, inputs should be cleared after a sign-in or a sign-up. 
If I sign-out, I don't want that the next user has to clear both inputs manually (or even If I don't who is the next user, that this one see my email and the password input filled).

I also use a password manager so I don't use the "Remember me" checkbox and I think most people don't use it anymore cause of the auto-completion of browsers. (And websites, like Facebook, don't have this checkbox anymore).

For the password input, I prefer when the password field is cleared when I put a wrong password. Cause I'll anyway try again completly. (There is only the windows login screen who does not clear password input).

**Comment by masonlouchart** [comment]
It seems we all agree that inputs must be cleared.
OSX too, does not clear de password input.

**Comment by masonlouchart** [comment]
PR #119 merged.
