### ISSUE TITLE
Warning when we click on "Forgot password" link

### ISSUE THREAD

**Issue by masonlouchart** [convoo/login-fire#124]
A warning appears when we click on the links "Forgot password" and "Nevermind, I remembered my password". We have to check where it comes from and if we can do something.

### Polymer 1
<img width="616" alt="capture d ecran 2017-06-23 a 23 37 25" src="https://user-images.githubusercontent.com/2325091/27501353-13a8e7ee-586d-11e7-8873-89a7c72f5ffa.png">

### Polymer 2
<img width="628" alt="capture d ecran 2017-06-23 a 22 48 43" src="https://user-images.githubusercontent.com/2325091/27500092-1fbbe924-5867-11e7-89a4-8260ad2af23d.png">

**Comment by Oupsla** [comment]
There are 2 empty on-tap listeners  

Here 
https://github.com/convoo/login-fire/blob/v2/login-fire-form.html#L199

And here
https://github.com/convoo/login-fire/blob/v2/login-fire-form.html#L225

**Comment by Oupsla** [comment]
Removing them fix this issue/warning :smile:

**Comment by masonlouchart** [comment]
@Oupsla 😮 Whaaaaat?! 🙄 ... Nice catch! 👍
