### ISSUE TITLE
Custom CSS variables not applied on progress bar

### ISSUE THREAD

**Issue by masonlouchart** [convoo/login-fire#153]
The custom CSS variable for applying a color on the progress bar (displayed when a sign in/out process is in progress) are not working with Polymer 1.

**Comment by Protoss78** [comment]
Hmm. That's strange. According to the 1.0 specs the default CSS variabe handling has not changed: https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-properties

Will try to reproduce that tomorrow and look into it as well.
