### ISSUE TITLE
Replace this.$$ with this.shadowRoot.querySelector for examples  -i.e. signOut()

### ISSUE THREAD

**Issue by davie-robertson** [convoo/login-fire#158]
I discovered (after some time) that the examples given for the signOut() method no longer work in Polymer 2 and above - as per https://www.polymer-project.org/2.0/docs/upgrade

Example given
`this.$$('login-fire-form').signOut();`
should be...
`this.shadowRoot.querySelector('login-fire-form').signOut();`

Happy to update the code/examples (in the next week or so) - leave this here to to match a pull request

**Comment by masonlouchart** [comment]
Thank you for your help. The login-fire v1 is a [hybrid element](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements) and use the legacy syntax.

**Comment by davie-robertson** [comment]
is it expected that the legacy syntax works on >v1?

**Comment by masonlouchart** [comment]
It works with Polymer v2. For Polymer v3 we'll rewrite the elements with new syntax (using [lit-html](https://github.com/polymer/lit-html)) and replacing Behaviors by Mixins.

**Comment by davie-robertson** [comment]
Thank you for the quick reply - I must be doing something else wrong as I did not work for me hence the ticket.
