### ISSUE TITLE
Consider using behaviors for shared properties

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#16]
We may want to use behaviors for shared properties with login-fire for both email and social logins.

**Comment by masonlouchart** [comment]
Like said in [this comment](https://github.com/convoo/login-fire/pull/47#issuecomment-274386261) this issue fixed on the branch `v2`.

**Comment by masonlouchart** [comment]
Close this one because it's done.
_Milestone for v1 has too much opened issues already fixed._
