### ISSUE TITLE
localesFile breaks localization

### ISSUE THREAD

**Issue by sundar-rajavelu** [convoo/login-fire#167]
The locales-file attribute breaks the localization functionality. Localization works as long as one uses the built-in languages defined in locales.html. The moment locales-file attribute is included, all the texts disappear from the login form. This bug can be seen even in the demo for Japanese language (@webcomponents.org).  
<img width="933" alt="screen shot 2018-05-09 at 12 38 23 pm" src="https://user-images.githubusercontent.com/38674104/39827501-1c400d64-5386-11e8-867c-644d23350b14.png">

**Comment by masonlouchart** [comment]
Thanks to point it out. 👍 

I'm currently working on the collection and I've fixed some issues. Maybe I can try to push the patch for this one sooner.

**Comment by sundar-rajavelu** [comment]
Thank you!
