### ISSUE TITLE
Email regex needs fix

### ISSUE THREAD

**Issue by JaySunSyn** [convoo/login-fire#175]
Hi, the regex doesn't match `j+hello@gmail.com`.

https://github.com/convoo/login-fire/blob/master/login-fire-form.html#L140

I guess it needs an urgent hotfix.

**Comment by masonlouchart** [comment]
You should be able to give you own Regex using the according attribute. PR are also welcome. Is there someone using the “+” in its email address? For real?🤭

**Comment by masonlouchart** [comment]
My apologies for my previous comment. I should have clicked on your link and have seen there is no attribute for the validation pattern of the email address.

We can fix the pattern and expose an attribute to customize it if needed.

**Comment by JaySunSyn** [comment]
Thank you :)

Yes, the plus sign is quite common for gmail. Try it out, it's quite cool.

Assuming this is your address: mason.louchart@gmail.com
This one will also land in your inbox: mason.louchart+github@gmail.com
Basically everything after the plus sign. 

You can use it to avoid/filter spam or signup with different email addresses without creating new accounts.

**Comment by masonlouchart** [comment]
😲 I don't know anything... 😞
