### ISSUE TITLE
Change value={{email:input}} to value={{email}}

### ISSUE THREAD

**Issue by polinom** [convoo/login-fire#18]
For some reasons when I install login-fire in to my application it does nor catch changes on email varialble. So I have to go to bower components and change this two lines:

``` html
      <paper-input id="emailInput" type="email" label="Email" value="{{emai:inputl}}" validator="email-validator" error-message="Invalid email address" required auto-validate></paper-input>
      <paper-input id="pwInput" type="password" label="Password" value="{{pw:input}}" required></paper-input>
```

to:

``` html
      <paper-input id="emailInput" type="email" label="Email" value="{{email}}" validator="email-validator" error-message="Invalid email address" required auto-validate></paper-input>
      <paper-input id="pwInput" type="password" label="Password" value="{{pw}}" required></paper-input>
```

I just remove `:input` from bindings and it starts working.

**Comment by sbeleidy** [comment]
Can you share the error you're getting? I remember it not working without adding `::input` and so we decided to follow it as shown in the docs here: https://www.polymer-project.org/1.0/docs/devguide/data-binding#two-way-native
