### ISSUE TITLE
[demo] Show full log in/out flow (form and each federated identity providers ?)

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#19]
In the modal examples, show the full flow of authentication.

On login, the dialog button disappears and a new button appears for logging out. That button logs out the user and therefore displays the login button again.

**Comment by timyhac** [comment]
+1 on this. My current implementation uses polymer's "dom-if" to solve.
```html
<template is="dom-if" if="{{!signedIn}}">
    <social-login-fire id="login" signed-in="{{signedIn}}" etc etc etc></social-login-fire>
</template>
<template is="dom-if" if="{{signedIn}}">
    <paper-button on-tap="_logout">Log Out</paper-button>
</template>
```
Would it make sense to have the option to have the "Log Out" functionality built in to the component?

**Comment by sbeleidy** [comment]
Hi @timyhac, Your current implementation is the expected/suggested one. We'll try to update the docs to make it even more clear and we'll track that in this issue. We'll update the demo to show the dom-ifs and a logout button implementation.

We'll also look into a logout button component but that is less likely.

Thank you for your feedback! We'd love to hear more about what you like and dislike about login-fire.

**Comment by sbeleidy** [comment]
@timyhac We might be adding a logout button component that might make things easier. You can follow along with #40 and #41 if you're interested.

**Comment by masonlouchart** [comment]
Done since a while.
