### ISSUE TITLE
Remove unnecessary demos

### ISSUE THREAD

**Issue by bkawk** [convoo/login-fire#22]
Logic...
If you don’t want email, use social 
if you don’t want social, use email
if you want both use login

On the login-fire demo page we should remove the demo's that dont feature email and social login
1. Narrow login-fire Demo with 2 options
2. Narrow login-fire Demo with emailPassword option only
3. Wide login-fire Demo with emailPassword option only

**Comment by sbeleidy** [comment]
Can you also add that statement in the documentation for each of the elements?

```
For email authentication only, use email-login-fire.
For social provider authentication only, use social-login-fire.
For both email and social provider authentication, use login-fire.
```
