### ISSUE TITLE
Mini social button option

### ISSUE THREAD

**Issue by bkawk** [convoo/login-fire#23]
After looking at the horizontal social login..

Allow requesting smaller social login buttons.
1. Remove the "Sign in with" part of the button text. 
2. Maybe make the padding/margins a bit smaller.
3. Maybe make the font size a bit smaller.

**Comment by sbeleidy** [comment]
![screen shot 2016-07-14 at 12 52 12 pm](https://cloud.githubusercontent.com/assets/1388511/16837170/e2280926-49c1-11e6-916d-8f1554b77bfc.png)

I'm guessing anonymously should be capitalized and we can make the buttons narrower but I think the font size is fine. Thoughts?

**Comment by sbeleidy** [comment]
![screen shot 2016-07-14 at 1 15 44 pm](https://cloud.githubusercontent.com/assets/1388511/16837693/2501d044-49c5-11e6-92e0-9342be6472b1.png)

I think this is better now.
