### ISSUE TITLE
login-fire reflected properties should work even if email-password is false

### ISSUE THREAD

**Issue by cineq** [convoo/login-fire#27]
Hi I am trying to use polymerfire with my project.
I try to bind information about sign in status:
```
            <login-fire google
                        facebook
                        mini
                        signedIn="{{signedInn}}"
                        app-name="domo">
            </login-fire>

            <template is='dom-if' if="{{signedInn}}">
                <p>Signed In</p>
            </template>

            <template is='dom-if' if="{{!signedInn}}">
                <p>Signed Out</p>
            </template>`
```

Unfortunately I am not able to see any of dom-if elements

**Comment by sbeleidy** [comment]
Hi @cineq , thank you for trying out login-fire.

I think the issue is that `signedIn` should be `signed-in`. The properties are camel-cased in the definition but are dashed-case in the HTML tag attributes (just like you did with `app-name`).

Please let me know if that fixes things.

**Comment by cineq** [comment]
Still not working. 
As I see on source code of loginfire it is:

```
        signedIn: {
          type: Boolean,
          readOnly: true,
          notify: true,
          computed: "_computeSignedIn(emailSignedIn, socialSignedIn)",
        }, 
```

I am also trying with function issigned:

```

            <login-fire google
                        facebook
                        mini
                        signed-in="{{signedInn}}"
                        app-name="domo">
            </login-fire>
            <template is='dom-if' if="{{isSignedIn(signedInn)}}">
                <p>Signed In</p>
            </template>
            <template is='dom-if' if="{{isSignedIn(!signedInn)}}">
                <p>Signed Out</p>
            </template>
        </div>
    </template>
</dom-module>
<script>
      Polymer({
          is: 'login-form',

          properties: {
              spinnerinfo: {
                  type: String,
                  notify: true,
              },

              signedInn: {
                  type: Boolean,
                  value: false,
              }
          },

          ready: function () {
              console.log("Login form ready");
              console.log(this.signedInn);
          },

          isSignedIn: function (signed) {
              return signed;
          },
      });
</script>
```

But still not working

**Comment by sbeleidy** [comment]
You shouldn't set the `signedInn` property.

What do you see in the console? And do you have your firsebase-app element set up correctly with the name="domo"?

**Comment by sbeleidy** [comment]
You can see how we use it here: https://github.com/convoo/convoo/blob/master/src/convoo-app.html#L249 and https://github.com/convoo/convoo/blob/master/src/convoo-login.html#L56

I'll be more than happy to troubleshoot this with you though. There may be issues with your firebase setup or other issues. Knowing what the console logs will be very helpful in figuring out the issue.

Also, are the buttons showing? What happens when you click them? Are you able to sign in and it's just not reflecting the signed-in value? Can you try the debug property? Giving more details will make it easier for us to help you find the issue.

Thanks

**Comment by cineq** [comment]
Hi sbeleidy,
Thanks for your help.

Buttons are showing up. Currently I am using two of them: google and facebook. 
There are no errors in console log, however when I am clicking Facebook button, this message log shows up:

```
code:"auth/account-exists-with-different-credential"
credential:Wf
email:"marcin.kurpiel@gmail.com"
message:"An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address."
```

I think that firebase-app is setup correctly since I am not seeing any errors, and I see user on firebase dashboard. 

I receive ""undefined" when I try to log property value

When I add "debug" attribute like:

```
            <login-fire google
                        facebook
                        mini
                        debug
                        signed-in="{{signedInn}}"
                        app-name="domo">
            </login-fire>
```

I see prints with properties, but not filled with anything

**Comment by cineq** [comment]
Here is link to the repo

https://github.com/cineq/domo-cordova/tree/polymer-fire/www/src

**Comment by sbeleidy** [comment]
I'll look through that in more detail later but since you are not using an email and password sign in can you try using social-login-fire instead of login-fire?

**Comment by sbeleidy** [comment]
Just ran your code and changed it to social-login-fire instead and it worked fine. 

The login-fire element is for both email and social login whereas if you only want one or the other you should use social-login-fire or email-login-fire.

That is the current way things are set up however, I understand the frustration that it should work with login-fire even if you don't want email. We'll use this issue to track getting that working correctly. 

In the meantime, please either use the `social-login-fire` element if you do not want email and password authentication or add the `email-password` property to `login-fire` and get email and password authentication as well.

Sorry for the inconvenience.

**Comment by cineq** [comment]
Thanks sbeleidy!

I have changed to social-login-fire and it works well.

I still see some issues related with facebook and google signIn process. 
When I signed in using Facebook as first everything works well, but if I sign in using google I am not able sign in via Facebook anymore.

This probably not related with login-fire, but more with firebase itself

**Comment by cineq** [comment]
I think it would be good if login-fire could react in way described in:
https://firebase.google.com/docs/auth/web/account-linking

Its just an idea

**Comment by sbeleidy** [comment]
You're welcome - glad I could help.

We should be able to link accounts that have the same email address under multiple providers following [this](https://firebase.google.com/docs/auth/web/account-linking). I'm not really sure if it's currently doable with firebase-auth or if we'll have to manually do it in JS but I've added #28 to look into it.

Thanks for the suggestion!
