### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#3]
Reset password link for email password section currently does nothing.

**Comment by polinom** [comment]
Let me dig in to it

**Comment by polinom** [comment]
Hey @sbeleidy I think we should should have space for successful messages. What do you think?
For example to say that email was send and you should go and verify your inbox. I know we could let this handle to end user.. however I'd rather have it built in. 
We could also use that to show that user was logged in / registered successfully.

**Comment by sbeleidy** [comment]
The idea is that others using this component should listen for changes to `signedIn` and handle it however they want. I'd rather minimize what we automatically do for everyone.

However, we can add another boolean attribute, `displaySuccessMessages` that defaults to false and would display an opinionated flow regarding what successful messages should display. If you're interested in this, we can track it on another issue. I think this makes the most sense for emailPassword but not for the other services. Let me know what you think.

**Comment by sbeleidy** [comment]
Sorry - I think I misunderstood. For the reset password section we should have a message section. You can add one just like the error section.

My comment was regarding just regular sign-in flow.

**Comment by sbeleidy** [comment]
@polinom if you'd like to discuss things further, we can use the gitter chat: https://gitter.im/convoo/login-fire
