### ISSUE TITLE
present sign out button if user is logged in

### ISSUE THREAD

**Issue by ryanwtyler** [convoo/login-fire#42]
when a user is signed in change the log-in button to a log out button.  thanks

**Comment by sbeleidy** [comment]
You can set up sign out using the signOut function of each of the components. You can hide and show the components using a dom-if template or hidden property using the signedIn variable that's exposed through the signed-in property. 

A good example is available here: https://github.com/convoo/login-fire/issues/19#issuecomment-268643673

We are also considering a logout component in #40  and #41  that can make things easier but you will still have to use a dom-if or hidden property.
