### ISSUE TITLE
[proposal] Consider remove the debug part

### ISSUE THREAD

**Issue by masonlouchart** [convoo/login-fire#44]
This is just my opinion. The "debug" part is very useful, when we need to debug. And because the element is working pretty well, in the most cases this is unfortunately useless. Moreover it brings noise to the useful source code and it adds a bit weight at the compiled app.

Maybe it could be possible to make it an separated element, usable locally but not included to the production code.

Same notice for the 2 sub-elements of `login-fire`.

**Comment by sbeleidy** [comment]
Thanks @LM450N , @bkawk what do you think?

**Comment by masonlouchart** [comment]
This is done on the branch `v2`.
