### ISSUE TITLE
[proposal] Turn the element into a collection

### ISSUE THREAD

**Issue by masonlouchart** [convoo/login-fire#45]
Hi!

I wanted just say I'm working on a fork of this element. It was restructured for integrating a shared behaviour and a new `login-fire-button` element that offers login and logout. There is a little work but I'll make a PR when everything will be ready. I hope it will please to you.

**Comment by sbeleidy** [comment]
Hi! Thank you, we were planning on doing that with the shift to polymer 2.

For the logout element please take a look at #41. 

We'd love to get your feedback and see what you're working on though so please share it whenever you're ready!!

**Comment by masonlouchart** [comment]
The proposed PR may be updated once again. I simply would like to add the missing unit tests. Please, feel free to open an issue on our fork to discuss about all changes.

**Comment by masonlouchart** [comment]
The merged PR fixed it.
