### ISSUE TITLE
Add localization to allow setting the text of the form buttons

### ISSUE THREAD

**Issue by masonlouchart** [convoo/login-fire#46]
I guess some developers would like to customize the sign-in and sign-up buttons. I mean, change the text. _For colours and theming there is another thread._

What do think about it?

**Comment by sbeleidy** [comment]
We'd be willing to add that with the current values as defaults. Would you want this for email-login-fire or social-login-fire as well?

**Comment by masonlouchart** [comment]
With my colleague we planned to implement a behaviour to allow web components to integrate easily translation providing their own dictionary. For the `social-login-fire` we would like to bring a default dictionary (with English and French). So, this issue was essentially about the `email-login-fire`.

At the end of week I'll create a pretty breaking PR for the repository ([see the commits](https://github.com/Hostabee/login-fire/commits/45-turn-element-into-collection)), so I suggest to wait a little if you want to merge it.

**Comment by masonlouchart** [comment]
This [commit](https://github.com/convoo/login-fire/commit/cd8dcd99cd0b5284a8bf49a8385dd5d9548c775d) closes the issue.
