### ISSUE TITLE
Upgrade to Polymer 2

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#48]

**Comment by masonlouchart** [comment]
@sbeleidy 
Isn't it solved by v1 that is an hybrid element or we'll wait for source code having Polymer 2 syntax to close this issue?

**Comment by masonlouchart** [comment]
This issue is fairly old and there hasn't been much activity on it. ⌛

**Comment by sbeleidy** [comment]
This should probably be upgrade to lit-element at this point.
