### ISSUE TITLE
Just one logout button

### ISSUE THREAD

**Issue by bkawk** [convoo/login-fire#55]
As the Log Out button's all do the same thing do we really need so many logout buttons?

I feel just one aligned bottom with the Sign In and Sign Out is enough.

There is also a small delay when clicking Log Out, maybe swap the Log Out logo for a spinner once clicked. This may only be relevant on slow internet connections like mine!

**Comment by masonlouchart** [comment]
I don't understand the question

>  do we really need so many logout buttons?

Login-out is a behavior. You can use the `login-fire-button` or even implement this behavior into you own element. You are not forced to use `login-fire-social` that has effectively too much logout buttons.

About that, I thought we could display only one button when the `login-fire-social` is on the signed-in state. I think I already have write something in the issues tracker about it.

**Comment by bkawk** [comment]
That sounds awesome, displaying just one button will be great!

**Comment by masonlouchart** [comment]
With a little effect of accordeon you know. But I'm not a Black Belt in CSS animations. 🥋

**Comment by masonlouchart** [comment]
I think this is done on the `v2` branch. Anyone to confirm?

**Comment by masonlouchart** [comment]
Isn't included in the release 1.0.0 ?
