### ISSUE TITLE
Change canSignOut to onlySignOut, onlySignIn

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#56]
canSignOut property should only focus on clickable sign out but should allow developer to use .signOut() method.

@LM450N do you have any objections to this?

**Comment by masonlouchart** [comment]
For me, the render must reflect the behavior. Or the behavior must follow the render, as you prefer.

This kind of button will be hidden or will disappear when the user will be signed in (by redirection or CSS tricks). So it can't be used to sign out the user.

The developer has to add another button, link or even a `login-fire-button` to let the user sign out from the app. Programmatically, he can sign out directly using the `firebase-auth` element.

Maybe you have a use case?

**Comment by sbeleidy** [comment]
We have a sign in button in the nav that opens a modal. When the user comes back, the modal disappears and there is a logout icon-button in the nav. There may sometimes be a split second where the modal is open and the user is logged in and it may look weird at times.

I think having the ability to use the same sign in to sign out as a function without signing out as a click may be useful.

We can add it as an additional boolean. One for signing out by clicking and one for signing out by function. I just don't see a point in time where I wouldn't want to be able to sign out using the function. There are many cases where I wouldn't want to sign out using a click. Thoughts?

**Comment by masonlouchart** [comment]
I'm still thinking if you are using the `login-fire-button` without the boolean _canSignOut_ you can't signing out with it because it's not its business. You can signing out using the `firebase-auth` element when the user click on the logout `icon-button`.

If it's a critical issue, the developer can create a custom component that contains the `icon-button` and implements the `login-fire-common-behavior` behavior or even use a `login-fire-button` element.

What I mean is it's not a `login-fire` element issue.

If you think it will be useful, you can do the change, it's not a big deal. 😉

**Comment by sbeleidy** [comment]
@LM450N If you get a chance, can you take a look at this and let us know how you'd implement it? I feel like adding another logout component defeats the purpose. Maybe we create a login-fire-button that's an icon-button and add an option to not display text? Or do you think this is too specific an example that we shouldn't be concerned with?

https://github.com/Photour/photour/blob/master/src/my-app.html#L238
https://github.com/Photour/photour/blob/master/src/my-app.html#L301
https://github.com/Photour/photour/blob/master/src/my-app.html#L182

We really appreciate your feedback!

**Comment by masonlouchart** [comment]
@sbeleidy In your case I guess you can replace the [line 302](https://github.com/Photour/photour/blob/master/src/my-app.html#L302) by this:

```javascript
document.querySelector('firebase-auth').signOut()
```

We could create a `fire-login-icon-button` element that is literally an `icon-button` which implements the `login-fire-common-behavior` behavior.

Moreover, we should replace the `canSignOut` attribute by `onlySignIn` and add the attribute `onlySignOut`. By doing this, all components implementing the `login-fire-common-behavior` behavior will be able to signing in or signing out or both.

_This would be my way to do it._ 😉

**Comment by sbeleidy** [comment]
That sounds great! Will try to get to both of those suggestions soon.

As always, thank you for your input!

**Comment by sbeleidy** [comment]
Split this idea into 2, see #73

**Comment by masonlouchart** [comment]
Only to be sure, this issue is closed by the commit [a87b617](https://github.com/convoo/login-fire/commit/a87b617cb8b48f901b9dec1eb9dd21349889d356).

**Comment by masonlouchart** [comment]
Close this one because it's done.
_Milestone for v1 has too much opened issues already fixed._
