### ISSUE TITLE
Show the sign in/out process is in progress

### ISSUE THREAD

**Issue by bkawk** [convoo/login-fire#64]
There is a painful pause when clicking a provider button, I think we should show a spinner

**Comment by Protoss78** [comment]
This is addressed in the PR I just provided and can be tried out in my current fork. I decided against the paper spinner and used the progress bar instead. Mainly for layout simplicity reasons.
Please have a look at it and let me know what you think. :-)

**Comment by masonlouchart** [comment]
Thank you @Protoss78 for your awesome work! 👏
