### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#69]

**Comment by masonlouchart** [comment]
There is no documentation about fired events _(signedin, signedout)_.

**Comment by masonlouchart** [comment]
I don't remember what it is about. The two events [seem documented since January](https://github.com/convoo/login-fire/blob/v2/login-fire-common-behavior.html#L413-L424). I guess we were talking about the README file.

What do you think?

**Comment by sbeleidy** [comment]
I think so - yeah. This issue is about documenting everything though as well.
