### ISSUE TITLE
Expose colors via customizable variables

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#7]
We should make it easy to customize all colors.
- [ ] Add customized colors
- [ ] Add customized colors demo
- [ ] Add preset dark theme

**Comment by masonlouchart** [comment]
As [proposed by @bkawk](https://github.com/convoo/login-fire/pull/47#issuecomment-274764236) in the thread of the merged PR, we could apply the app theme on the `login-fire-button`. By extension, the developer will be able to use a custom style using default mixins.

What do you think about it?

**Comment by sbeleidy** [comment]
Yep, that's the idea.
