### ISSUE TITLE
Add noRepeatPassword with view option

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#72]
Add the noRepeatPassword property that allows for the option to show/hide the password on sign up instead of a re-enter password box. 

See http://jsbin.com/cawija for implementation

**Comment by masonlouchart** [comment]
Is this [commit 5a8e7eea](https://github.com/convoo/login-fire/pull/75/commits/5a8e7eea420058084d1a9175b99e6c05e2e08684) adding the feature?

**Comment by sbeleidy** [comment]
Yes!
