### ISSUE TITLE
Sometime buttons not responding. 

### ISSUE THREAD

**Issue by cappittall** [convoo/login-fire#78]
First of all thank you for your great helps for developers. I have faced the issue and solution was : 
(May be I avoid something but in case I like to share the issue. Sorry in advance if mistake cause from me.) 

http://stackoverflow.com/questions/42648043/polymer-paper-button-sending-arguments-on-tap-works-but-sometime-not . 

Regards

**Comment by sbeleidy** [comment]
Sorry @cappittall, just realized I never messaged you about this. Thank you for reporting! We've added a fix in the latest release.
