### ISSUE TITLE
Sign in with new account -> signup as an option

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#8]
We currently have the default behavior for a sign in with a non-existing account as signing them up.
We should make this as an option and decide on which option would be the default.

Pros of automatically signing up:
- Simpler flow
- Option to eliminate a button

Cons of automatically signing up:
- Typo in email address leads to a terrible UX where the user signs in as a new account thinking they accessed their old account
- [ ] `autoSignUp` attribute
- [ ] Decide on default option
- [ ] Reconsider having one button for Sign up / Sign in when using autoSignUp - instead of 2 buttons - this may be another attribute

**Comment by polinom** [comment]
Hmmm.. I don't know... I think we should have two inputs for the password when signing up.

**Comment by sbeleidy** [comment]
I think having the confirm password input would require #11. This issue would just be for setup of auto-sign-up as an attribute.
