### ISSUE TITLE
Support accessibility in reverse property for login-fire

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#81]
Should we remove reverse and explain/demo that you can apply that with a mixin?

**Comment by masonlouchart** [comment]
Personally, I always prefer the declarative way over the programmatic one. In this case, if CSS can do the job, I would prefer use it instead of use JS.

**Comment by sbeleidy** [comment]
The property applies a class but instead we could just expose a mixin and tell people to use that. My concern is that many may not be familiar with applying custom styles and want to just pass in a property instead.

My other concern is that applying it with CSS right now is terrible for accessibility. It goes to items on the right first then goes back to items on the left. The element order in the dom needs to be updated instead.

**Comment by masonlouchart** [comment]
I think we don't have to design Web Components according to the fact people don't know CSS custom variables and mixins. Learning new things is half part of the developer job.

But, accessibility is a really serious topic. If using mixins breaks it, maybe it's better to wait a little and study it before remove the property.

**Comment by sbeleidy** [comment]
The current property just applies a mixin. It doesn't support accessibility right now either. We still need to add that - which is why I was thinking of removing the property. Having the property makes it seem like we've handled it for the developer when all we do is add the reverse mixin - so they're better off just adding that.

If we are to support it - which I also think we should, I was thinking of the following element to make: 

``` html
<reverse-element reverse="[[reverse]]">
    <a></a>
    <b></b>
    <c></c>
</reverse-element>
```

Where based on the reverse property value it reverses the dom order of the children.
So if reverse is true it displays:
```html
    <c></c>
    <b></b>
    <a></a>
```
If false:
```html
    <a></a>
    <b></b>
    <c></c>
```

 I'm not 100% sure how to do that yet but I think if it were to exist it would help us (and maybe others) significantly.

**Comment by sbeleidy** [comment]
I created [reverse-element](https://github.com/convoo/reverse-element) - [demo](https://www.webcomponents.org/element/convoo/reverse-element)

We can use it for this issue and hopefully it'll fix it.

**Comment by masonlouchart** [comment]
I think this _"feature"_ should be done using reversed [iron-flex-layout](https://www.webcomponents.org/element/PolymerElements/iron-flex-layout) instead of create a new one.

**Comment by sbeleidy** [comment]
That is what we were already doing. It breaks accessibility because that's just CSS. Unless I'm missing something.

**Comment by masonlouchart** [comment]
Maybe this issue should be reported to the Polymer team?

**Comment by sbeleidy** [comment]
There's nothing they can do about it. The role of their component is CSS classes that are easy to use. 

When you hit tab to go through inputs it goes based on the dom order not the visual order. Their component just chances the visual, mine changes the dom order.

**Comment by sbeleidy** [comment]
I updated the [demo](https://www.webcomponents.org/element/convoo/reverse-element) to use paper-inputs so you can try tabbing through it.

**Comment by masonlouchart** [comment]
They are well two different features. But I don't understand the purpose to have this kind of element. The developer just has to change the order of its elements. The order (almost) never changes dynamically. This seems to be a very specific use case.

__I just seen that this issue is related to the v1 of the login-fire__ 😖. I wasn't understanding it because in the _v2_ I changed the way to define providers to be used and it allows specify the order. I'm sorry about make you lost your time.

**Comment by sbeleidy** [comment]
Sorry for the confusion. The v2 branch is actually 1.0 I messed up the version because I had thought we launched 1.0 when we actually only launched 0.1.0.

I agree that this is useless with login-fire-social since you can specify the order. This is mainly for the login-fire element only - where you are displaying both the form and the social providers. By default, the form shows on the left and the social providers on the right but you may want to reverse that. In that case, we currently use the layout-reverse CSS mixins which change the visual order. If you try to tab through the elements what you get is that the first tab will go to the form and then after you tab through it it goes to the social providers (even though they've switched order). This is because tabbing follows the dom order and not the visual order.

My way around that is to use the reverse element which changes the dom order so you get both the visual order and you can tab through the social providers first and then the form as you'd expect.

Sorry again about the confusion, I hope this better explains my take on it. I think I will also start some labels that may be helpful that are used for each tag so it's more clear what we're discussing and I should have also written a better description initially. Thanks for taking the time to go through this!

**Comment by masonlouchart** [comment]
Ok, I got it!

I have nothing to say except I'm totally agree to use your new element in this case. It's simply a container used by `login-fire` to organise the both form and social provider. Awesome!

Thanks for the labels!

**Comment by sbeleidy** [comment]
Great!

**Comment by masonlouchart** [comment]
Close this one because it's done.
_Milestone for v1 has too much opened issues already fixed._
