### ISSUE TITLE
Remove href from form signup toggle

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#83]
The current href was added for #68 but it actually breaks the page since it moves to the top when clicked.  We should handle that better.

**Comment by masonlouchart** [comment]
We can also disable links instead of replace them by buttons if you prefer.

**Comment by sbeleidy** [comment]
The purpose of this issue is to remove the link effect moving the page to the top but maintaining the ability to click on a link using the spacebar when focused so that we maintain accessibility. I'm not sure what you mean by disabling links but would that accomplish the above?

**Comment by masonlouchart** [comment]
I should say disable the "HREF". I mean, preserve the click and our callback bu prevent the default behavior.

I should admit I already tried it nut it's not an easy way. It requires extra JavaScript and I don't really like the idea to use [anchors as placeholder](https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element).

Do you prefer keep buttons or try to use anchors?

**Comment by masonlouchart** [comment]
It was fixed [here](https://github.com/convoo/login-fire/commit/93fa24ac24922230654fbb08b93f19f43558b8c8)
