### ISSUE TITLE
Make sure all messages are localized

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#85]
This applies to all errors and success messages that show up above the form.

**Comment by masonlouchart** [comment]
I'm sure they are not. Just seen one in the `login-fire-form` element.

line 220:
```html
<paper-input ...
error-message="Invalid email address"
...></paper-input>
```

**Comment by masonlouchart** [comment]
In the `login-fire-form` on the icon to show/hide the password:

```html
<paper-icon-button ...
        title="Hold to view password text">
</paper-icon-button>
```

**Comment by masonlouchart** [comment]
PR #127 merged.
