### ISSUE TITLE
Polymerfire : app/duplicate-app

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#86]
Hello,

Since this morning I got a really strange error (I have made a bower update I think).
I don't know if it comes from login-fire or polymerfire

I have started my project from the polymer-shop example and I have created a page to include login-fire.
My firebase-app is initialized in the root page (shop-app with an iron-pages inside).
When I import login fire in the login page (or in the root page), I got a really strange stack trace : 

![Stacktrace loginfire](https://cloud.githubusercontent.com/assets/15279620/23897749/9cab2066-08ae-11e7-8b09-76b8ab153d55.png)

I continued the searches and noticed that this error appeared when I included firebase-auth to a page.

I have also tried to not include login-fire directly, but as a lazy-ressources, but in this case login-fire don't find my firebase-app : "No app configured for firebase-auth!"

I have also tried with your others branches but still the same error.

Thank you for your help !

**Comment by Oupsla** [comment]
Polymer-cli : 0.17.0

"polymer": "^1.8.1",
"polymerfire": "^0.10.3",
"login-fire": "^0.1.5",
"app-storage": "^0.9.8",
"webcomponentsjs": "^0.7.24",

**Comment by Oupsla** [comment]
I have created a new instance of firebase in the firebase console and now it is working like a charm.

I close this issue :)

**Comment by sbeleidy** [comment]
Hi @Oupsla, thank you for reporting this. I'm not sure I get what the error was. Was it just setting the firebase-app name and using that?
I'm guessing you would need to pass the `app-name` to `firebase-auth` that you use for `login-fire` too.

**Comment by Oupsla** [comment]
After some minutes with my new firebase project, the bug has reappeared magically without chaning anything...

I wonder if this is not the activation of Firebase functions (that I begin to use) that causes this ... I have sent a support email to firebase and I'm waiting their answer

**Comment by Oupsla** [comment]
Eveything is working great with login-fire (so I imagine having it initialized good) for at least 10min when I deploy it (and locally). Then I got this stacktrace when I try to connect

**Comment by Oupsla** [comment]
![capture du 2017-03-14 15-20-08](https://cloud.githubusercontent.com/assets/15279620/23905395/3921f278-08cb-11e7-9a82-b64844b6c2f0.png)

**Comment by sbeleidy** [comment]
It looks like you may have some of the following from the first error log:
1. Not loading the polyfills - hence "HTMLImports is not defined"
1. Defining firebase-app twice with same name - hence "Duplicate app" error

From second error log:
Are you lazy loading your firebase-app definition? If so, try defining the firebase-app in index or your main app?
Also might be a wrong import file path - see https://github.com/Polymer/polymer/issues/1905#issuecomment-113231901

**Comment by Oupsla** [comment]
I'm loading and defining my firebase-app in my main app, only one time (that's why this error intrigues me).

I really don't understand why it is working for 10min, then everything about login bug (without changing anything).

**Comment by sbeleidy** [comment]
And you're using the same app-name which is really weird too. Sorry I couldn't help. I hope you manage to figure this out.

**Comment by Oupsla** [comment]
Yes, I'll wait the answer of the firebase support and update this message with a solution (I hope) for futur users 


EDIT : To keep you up-to-date, this error seems to appear only when I do a firebase deploy (hosting).

**Comment by sbeleidy** [comment]
That would be awesome - thank you!

**Comment by Oupsla** [comment]
Ok problem resolved !

It was a problem with the service-worker and the firebase-auth (I don't know why my problem was also trigger locally after a deploy).

You just have to add : navigateFallbackWhitelist: [ /^\/home\//, /^\/other\// ] (in the sw-precache-config.js)

Related to https://github.com/Polymer/polymer-build/issues/35

**Comment by sbeleidy** [comment]
Great! Thank you for sharing!
