### ISSUE TITLE
Require a strong password

### ISSUE THREAD

**Issue by bkawk** [convoo/login-fire#87]
if the user is signing up with email and password, I'd like an option to require a strong password, more than 7 characters long, must have 1+ upper case and must have 1+ special characters.

**Comment by sbeleidy** [comment]
Maybe we add a regex for passwords with a passwordRegex property? http://stackoverflow.com/questions/5142103/regex-to-validate-password-strength

**Comment by bkawk** [comment]
I like the ability to get specific with a regex, but I think some users would like a quick property to make it strong to a default level too, some users see regex and give up instantly

**Comment by sbeleidy** [comment]
Okay so we can add a decent default and then add the regex? We can link to that stackoverflow question in the docs as well.

My only concern is around error messaging if the password isnt good enough.

Also, do you want this/think it should be in 1.0 or for later?

**Comment by sbeleidy** [comment]
Or were you thinking of having something like the following properties instead:

pwMinLength, pwMinUpper, pwMinLower, pwMinSpecial, pwMinNumber? 
Having these would help with error messages as well.

**Comment by bkawk** [comment]
Maybe we could allow the user to pass an object and we construct the regex for them?
{"strong": 'basic'}
{"strong": 'military'}
{"strong": 'custom', "uppercase":2, "special": 3, "digits": 2, "lowercase": 2, "minLength": 7}

The timing I have no urgency, but I just came across this need

**Comment by sbeleidy** [comment]
ok so maybe those properties and a pwPreset that overrides these values? The preset would have to be one of a few options mabye basic, advanced and military or something. Any ideas for the preset names and what they should be? Maybe there's some standards out there we can check out.

**Comment by bkawk** [comment]
I've not seen any names standardized so maybe we just make up a few and define them. 

Strong could be min length of 8 and 1 uppercase and 1 special and one number
Military could require min 16 characters with 8 being special or digits

If we are going to attempt to secure passwords we should maybe require a captcha if the user fails to login 3 times or something alike?

**Comment by sbeleidy** [comment]
Looks like captcha requires a server side implementation and firebase doesnt really support it (was thinking maybe a firebase function but that might mean we have to create our own implementation of auth which is not a good idea).

Another thing we could do is collect the number of failed sign in attempts and just report that back in a property/attribute. We would also fire a "failed-sign-in" event.
