### ISSUE TITLE
Programmatically trigger connection

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#95]
Hello, 

Is there a way to trigger the connection (anonymously in my case) programmatically ?
I did not see any method except the one that disconnects the user.

Thank you !

**Comment by sbeleidy** [comment]
Hi @Oupsla,

There currently isn't a way to do that other than simulating a tap event using JS. In login-fire 1.0 however you will be able to invoke the `signIn` method to do so.

Hope that helps!

**Comment by Oupsla** [comment]
Hello @sbeleidy ,

Ok thank you for the information !
Great component by the way !

**Comment by Oupsla** [comment]
After a few tries, I was unable to select the anonymous login button in the shadow root :disappointed: 

Do you have any idea how to proceed (from the login-fire element) ?

**Comment by sbeleidy** [comment]
One way to go around this may be to use the `_signIn(e)` function from social-login-fire. You'd have to pass in an object with a target property that is an HTML node that has an attribute of `data-auth="#anonymous"`.
This is directly looking at the implementation we have [here](https://github.com/convoo/login-fire/blob/master/social-login-fire.html#L338). Sorry, there isn't really a better way of doing that now.

Hopefully, 1.0 will be out soon and there would be an easier way to do that.

**Comment by masonlouchart** [comment]
@Oupsla With my PR you'll be able to call `signInWith('anonymous')` on the `login-fire` element to trigger an anonymous connection.

_All providers brought by the `login-fire` element can be used._

**Comment by Oupsla** [comment]
Really nice, thank you !
